//
//  ClipboardMonitor.swift
//  CopyPasteMemory
//

import AppKit

// macOS NO avisa cuando el portapapeles cambia (no hay "notificación push").
// La única forma de enterarse es preguntar cada X tiempo: "¿ha cambiado algo?".
// Esta clase hace justo eso: pregunta cada 0.4s y, si detecta un cambio,
// lee el contenido nuevo y lo reporta hacia fuera mediante `onNewContent`.
final class ClipboardMonitor {
    // NSPasteboard.general es "el portapapeles del sistema" — el mismo que usa
    // Cmd+C/Cmd+V en cualquier app. No lo creamos nosotros, solo lo leemos/escribimos.
    private let pasteboard = NSPasteboard.general
    private let pollInterval: TimeInterval
    private var timer: Timer?

    // changeCount es un número que macOS incrementa cada vez que algo se copia.
    // Guardamos "el último valor que vimos" para poder comparar en cada tick del timer.
    private var lastChangeCount: Int

    // Algunos gestores de contraseñas (ej. 1Password) marcan sus copias con estos
    // "tipos" especiales en el portapapeles para pedir a herramientas como la
    // nuestra que NO las guarden en el historial. Es una convención de la
    // comunidad (org.nspasteboard.*), no una API oficial de Apple.
    private static let doNotRecordTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    // Si alguien copia una imagen gigante, la reducimos a como mucho 2000px
    // de lado, para no acumular cientos de MB en memoria con solo 25 items.
    private static let maxImageDimension: CGFloat = 2000

    // Closure (función) que se ejecuta cada vez que detectamos contenido nuevo.
    // La rellena quien use esta clase (en nuestro caso, AppDelegate).
    var onNewContent: ((ClipboardContent) -> Void)?

    init(pollInterval: TimeInterval = 0.4) {
        self.pollInterval = pollInterval
        // Al arrancar, anotamos el changeCount actual para no confundir
        // "lo que ya había copiado antes de abrir la app" con "contenido nuevo".
        self.lastChangeCount = pasteboard.changeCount
    }

    // Arranca el temporizador que llama a poll() repetidamente.
    func start() {
        timer?.invalidate() // por si ya había uno corriendo, lo paramos primero
        timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            // [weak self] evita que el timer mantenga viva esta clase para siempre
            // (si no, sería una referencia fuerte que nunca se libera de memoria)
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    // La usa ClipboardHistoryStore justo después de escribir algo en el
    // portapapeles (cuando el usuario elige un item del historial), para que
    // el siguiente poll() no confunda "lo que acabamos de escribir nosotros
    // mismos" con "algo nuevo que el usuario copió".
    func acknowledgeExternalWrite() {
        lastChangeCount = pasteboard.changeCount
    }

    // Se ejecuta cada 0.4 segundos.
    private func poll() {
        let currentChangeCount = pasteboard.changeCount
        // Si el número no ha cambiado, no ha pasado nada — salimos ya (barato).
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        // Si es una copia "protegida" (ej. una contraseña), la ignoramos.
        guard !containsDoNotRecordMarker() else { return }

        // Intentamos leer el contenido como texto o imagen; si no reconocemos
        // el tipo (ej. un archivo copiado desde Finder), no hacemos nada.
        guard let content = readContent() else { return }

        // Avisamos a quien nos esté escuchando (AppDelegate → guarda en el store)
        onNewContent?(content)
    }

    private func containsDoNotRecordMarker() -> Bool {
        guard let types = pasteboard.types else { return false }
        // `types` es la lista de "formatos" en los que el portapapeles ofrece
        // el contenido actual (ej. texto plano, RTF, PNG...). Comprobamos si
        // alguno coincide con los marcadores de "no guardar".
        return types.contains { Self.doNotRecordTypes.contains($0.rawValue) }
    }

    private func readContent() -> ClipboardContent? {
        let types = pasteboard.types ?? []

        // Primero comprobamos si hay una imagen (tipos .tiff o .png disponibles)
        if types.contains(.tiff) || types.contains(.png),
           let image = NSImage(pasteboard: pasteboard),
           let pngData = Self.normalizedPNGData(from: image) {
            return .image(pngData)
        }

        // Si no era imagen, probamos a leerlo como texto plano
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            return .text(string)
        }

        // No reconocemos el contenido (ej. un archivo, o algo vacío)
        return nil
    }

    // Redimensiona la imagen si hace falta y la convierte a PNG comprimido.
    private static func normalizedPNGData(from image: NSImage) -> Data? {
        let size = image.size
        guard size.width > 0, size.height > 0 else { return nil }

        // Factor de escala: 1.0 si ya es pequeña, o menor que 1 si hay que reducirla
        let scale = min(1.0, maxImageDimension / max(size.width, size.height))
        let targetSize = NSSize(width: size.width * scale, height: size.height * scale)

        // "Dibujamos" la imagen original dentro de un lienzo del tamaño reducido
        let resized = NSImage(size: targetSize)
        resized.lockFocus() // empieza a dibujar sobre este NSImage
        image.draw(
            in: NSRect(origin: .zero, size: targetSize),
            from: NSRect(origin: .zero, size: size),
            operation: .copy,
            fraction: 1.0
        )
        resized.unlockFocus() // termina de dibujar

        // Convertimos el resultado a bytes PNG
        guard let tiffData = resized.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData) else {
            return nil
        }
        return bitmap.representation(using: .png, properties: [:])
    }
}
