//
//  ClipboardMonitor.swift
//  CopyPasteMemory
//

import AppKit

/// Polls NSPasteboard.general for changes (there is no push notification API for it)
/// and reports newly copied text/image content.
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private let pollInterval: TimeInterval
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Marker types used by password managers (e.g. 1Password) to opt sensitive
    /// copies out of clipboard-history tools. See org.nspasteboard.* convention.
    private static let doNotRecordTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private static let maxImageDimension: CGFloat = 2000

    var onNewContent: ((ClipboardContent) -> Void)?

    init(pollInterval: TimeInterval = 0.4) {
        self.pollInterval = pollInterval
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call after writing to the pasteboard ourselves, so the next poll doesn't
    /// treat our own write-back as newly copied content.
    func acknowledgeExternalWrite() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        guard !containsDoNotRecordMarker() else { return }
        guard let content = readContent() else { return }
        onNewContent?(content)
    }

    private func containsDoNotRecordMarker() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.doNotRecordTypes.contains($0.rawValue) }
    }

    private func readContent() -> ClipboardContent? {
        let types = pasteboard.types ?? []
        if types.contains(.tiff) || types.contains(.png),
           let image = NSImage(pasteboard: pasteboard),
           let pngData = Self.normalizedPNGData(from: image) {
            return .image(pngData)
        }
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            return .text(string)
        }
        return nil
    }

    private static func normalizedPNGData(from image: NSImage) -> Data? {
        let size = image.size
        guard size.width > 0, size.height > 0 else { return nil }

        let scale = min(1.0, maxImageDimension / max(size.width, size.height))
        let targetSize = NSSize(width: size.width * scale, height: size.height * scale)

        let resized = NSImage(size: targetSize)
        resized.lockFocus()
        image.draw(
            in: NSRect(origin: .zero, size: targetSize),
            from: NSRect(origin: .zero, size: size),
            operation: .copy,
            fraction: 1.0
        )
        resized.unlockFocus()

        guard let tiffData = resized.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData) else {
            return nil
        }
        return bitmap.representation(using: .png, properties: [:])
    }
}
